name: humps
description: A Dart package for converting map keys between camelCase and snake_case. Useful for converting between JSON and Dart field names.
version: 1.0.1
repository: https://github.com/azizndao/humps

environment:
  sdk: ^3.2.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
